### ISSUE TITLE
[bug]: bulkDelete not emitted

### ISSUE THREAD

**Issue by jacopobonomi** [ComfortablyCoding/strapi-plugin-io#29]
### What issue are you experiencing?

if you delete from the collections page an entry the event delete is not emitted, only inside the page of the single entity.

### What version of the plugin are you using?

1.1.1

### What strapi version are you using?

v4.3.0-beta.2

**Comment by ComfortablyCoding** [comment]
Hmmm I believe a delete from the collection page does a bulkDelete of sorts, even if it's one entry. I don't believe we are listening for those, will have a look into it.

**Comment by zguig52** [comment]
Hi, just did some tests. This is working. Subscribers receive the delete events, even if done from the admin dashboard.
The only issue is related to the permission propagation model used by the plugin. Subscribers shall have the delete permission to receive the event, even if you don't want them to delete some items.
There might be some discussions on this, as you might want to have subscribers only having find permissions, but in order to update their display, they have to receive create, update and delete events also.

**Comment by ComfortablyCoding** [comment]
#36 should fix this issue. It looks like only the number of deleted records are returned on this event, not sure how useful it is. I do not know if this is something that changed in v4.
